In [1]:
import vocab
import re

import torch
import torch.nn as nn
import torch.nn.functional as F

/Users/outbell/Ajay/DeepLearning/GenAI/smallGPT/.venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


In [25]:
a = torch.tensor([[1.3456, 2.5354, 3.5787, 4.2342, 5.0788]])
a.shape

torch.Size([1, 5])

In [23]:
# Normal approach
sum =  a.sum(dim=1)
a/sum

tensor([[0.0802, 0.1512, 0.2134, 0.2524, 0.3028]])

# General approach

In [26]:
max = a.max(dim=1).values
dev = a-max
dev

tensor([[-3.7332, -2.5434, -1.5001, -0.8446,  0.0000]])

In [27]:
norm = dev.exp()
norm

tensor([[0.0239, 0.0786, 0.2231, 0.4297, 1.0000]])

In [28]:
sum = norm.sum()
sum

tensor(1.7554)

In [29]:
inv = sum**-1
inv

tensor(0.5697)

In [31]:
probs = norm*inv
probs

tensor([[0.0136, 0.0448, 0.1271, 0.2448, 0.5697]])

In [37]:
-probs.log()

tensor([[4.2959, 3.1061, 2.0628, 1.4073, 0.5627]])

In [2]:
xb = torch.tensor([4, 2, 17, 23, 2])
xb.shape

torch.Size([5])

In [9]:
C = torch.randn(30, 2).unsqueeze(0)
xb_enc = F.one_hot(xb, num_classes = 30).unsqueeze(2)
print(C.shape, xb_enc.shape, xb_enc)

torch.Size([1, 30, 2]) torch.Size([5, 30, 1]) tensor([[[0],
         [0],
         [0],
         [0],
         [1],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [1],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0]

In [11]:
demb = C * xb_enc
demb.shape

torch.Size([5, 30, 2])