In [1]:
import vocab
import re

import torch
import torch.nn as nn
import torch.nn.functional as F

/Users/outbell/Ajay/DeepLearning/GenAI/smallGPT/.venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


In [2]:
torch.tensor([0.12], dtype =  torch.float32) * 0

tensor([0.])

In [5]:
word = torch.randn(1, 6)
word

tensor([[-0.6323, -0.5521,  0.6471,  1.0933, -0.3958, -0.1496]])

In [7]:
word.view(1, 2, 7//2)

tensor([[[-0.6323, -0.5521,  0.6471],
         [ 1.0933, -0.3958, -0.1496]]])