In [1]:
import vocab
import re

import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
torch.tensor([0.12], dtype =  torch.float32) * 0

tensor([0.])

In [5]:
word = torch.randn(1, 6)
word

tensor([[-0.6323, -0.5521,  0.6471,  1.0933, -0.3958, -0.1496]])

In [7]:
word.view(1, 2, 7//2)

tensor([[[-0.6323, -0.5521,  0.6471],
         [ 1.0933, -0.3958, -0.1496]]])